# Generated by Django 5.0.10 on 2025-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_project_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Key features (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, help_text='Comma separated list of technologies used', null=True),
        ),
    ]
